### PR TITLE
Features

### PR DESCRIPTION
**Pull request by ridgekimani**
I have written tests for login and signup functionality.. You can check it out

### CODE REVIEW

**Comment by kaka-ruto** [comment]
Great work Ridge. Just make your commit messages be in present tense, like "Remove test module", instead of "Removed". But nice work.

**Comment by NaomiMariga** [comment]
Are the tests working as expected?

**Comment by briankabiro** [comment]
Great job. I think Collins has pointed out what you need to do about the commits

**Comment by NaomiMariga** [comment]
Keep it up and keep going

**Comment by ridgekimani** [comment]
Yes... The tests are working

**Comment by ridgekimani** [comment]
Thank you.. I will try to use present tense

**Pull request merged**
